In [16]:
import torch
import torch.nn as nn

In [17]:
a = torch.tensor([1,0,1,1,0,1,0,1,1])
f1 = a.nonzero().reshape(-1)
f2 = f1[2:5]

In [3]:
f1

tensor([0, 2, 3, 5, 7, 8])

In [4]:
f2

tensor([3, 5, 7])

In [64]:
for i in range(len(f2)):
    f1 = f1[f1!=f2[i]]

In [65]:
f1

tensor([0, 2, 7, 8])

In [8]:
f1[f2]

tensor([7, 8])

In [17]:
a

tensor([0, 0, 0, 0, 0, 0, 0, 1, 1])

In [27]:
x1[:, None]

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [2]:
a =  torch.tensor([0.1, 0.5, 0.4, 0.3]).reshape(1, -1)

In [3]:
a

tensor([[0.1000, 0.5000, 0.4000, 0.3000]])

In [4]:
b= torch.tensor([2])

In [5]:
b

tensor([2])

In [5]:
a.shape

torch.Size([9])

In [37]:
b = a.expand(20,-1)

In [38]:
b

tensor([[1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1]])

In [40]:
b.shape

torch.Size([20, 9])

In [43]:
c = b.transpose(0,1)

In [44]:
c.shape

torch.Size([9, 20])